name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload Static Website
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Utilizat pentru comentarii pe pull request-uri
          action: "upload"
          app_location: "/"        # Dacă index.html este în rădăcină
          api_location: ""         # Lasă gol dacă nu ai API
          output_location: ""      # Lasă gol dacă nu ai build (ex: React, Vue)
