name: Azure Static Web Apps CI/CD

pr:
  branches:
    - main
trigger:
  branches:
    - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build And Deploy Job
    steps:
      - uses: actions/checkout@v3
      - name: Upload artifact for static web apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"             # <- rădăcina proiectului (unde ai index.html)
          api_location: ""              # <- gol, nu ai backend
          output_location: ""           # <- gol, că nu folosești build
