name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Upload Static Website
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_BEACH_01539401E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ####### Opțional:
          ####### app_location: "/"  # dacă fișierele index.html și altele sunt în rădăcina proiectului
